version: '3'

services:
  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:14-alpine3.16
    container_name: postgres
    environment:
      - POSTGRES_USER=vijay
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=redis
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db/postgres/:/var/lib/postgresql